language: node_js
node_js:
  - lts/*
before_deploy:
  - pip install --user awscli
deploy:
  - provider: script
    skip_cleanup: true
    script: "./release"
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - secure: ZY+gzo1T46jFp88RViVnalHCr12zl1Ue7GXBwR+Cg7BwHtHrtr2k4yd88+5TWXGz3JKIyqQHxJi/SBdYBEAvyD6wBtyvgcvi5sV8EylIJwragzBJ3+muJUCiVyxD9UGeUNRdFU4yCVgDhcXhfRK5X11uD8vHpYCUlTrIoMhgaCqLcTQ7KR2teHmmz+K1VOaYUiY+BBKZnZ4F0QoJiO+58BPXVlfxfXFvvmB439G8wESMgdpTwUXfGTxMPtf/BXSM94D8llxwyagsh1QLF4fv2w+NJNRixdVgKFbAbO/1onFlFbL0p9Kn4jVF0ymm9ABPYV1Xof5AjuoOXs9aFVxdQJ+AkI6m4gTMYtC7TG/F6uO5NkFShG4bu4bKLaBmI4Ja2r59A/5RS1sBt1m6xjd4phMB1+wJYQim1hEVtqnFpfa/VsdSU+wdrhnI7MooQ0P2VpStlmAiKl54qIdDt8COtNJpRdFXOo38bvBYCB+V0q3FSvRC12GOATM5zw6KpAJoENqGcT2/R/fT4COM9s595GXmWvVWkeb547FT9QOSQIgYcCttu+dRbMtFhZMwpRBZX0rvdnXI36O4V4w+CrjDpsalA4u6gQd4N6hAs47yQR7X2R/Ja3RJ4N0xKNzGlQQqtfgjGVlNyuhhWfNbhZ+MELngHJZH7pHj6IfwDsRTRco=
