language: node_js
node_js:
  - lts/*
before_deploy:
  - pip install --user awscli
deploy:
  - provider: script
    skip_cleanup: true
    script: "./release"
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
